# Generated by Django 3.2.7 on 2021-09-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='day',
            new_name='Select_Day',
        ),
    ]
