# Generated by Django 3.2.7 on 2021-09-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_rename_day_table_select_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='name',
            new_name='Full_Name',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='persons',
            new_name='How_Many_Persons',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='phone',
            new_name='Phone_Number',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='hour',
            new_name='Select_Hour',
        ),
    ]
