# Generated by Django 3.2.7 on 2021-09-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0007_food'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dinner',
            new_name='Meal',
        ),
        migrations.DeleteModel(
            name='Break',
        ),
        migrations.DeleteModel(
            name='Dessert',
        ),
        migrations.DeleteModel(
            name='Lunch',
        ),
    ]
