# Generated by Django 3.2.7 on 2021-09-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0010_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos')),
                ('name', models.CharField(max_length=100)),
                ('admin', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=1000)),
            ],
        ),
    ]
