# Generated by Django 3.2.7 on 2021-09-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0014_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
